### ISSUE TITLE
The l2-address-lookup-table cannot be modified on E/T

### ISSUE THREAD

**Issue by sylane** [openil/sja1105-tool#27]
From the documentation `UM10944 Software user manual for SJA1105TEL`, on the E/T, the `l2-address-lookup-table` only have the fields `VLANID`, `MACADDR`, DESTPORTS`, ENFPORT` and  `INDEX`.

`sja1105-tool` requires the fields `tsreg`, `mirrvlan`, `takets`, `mirr`, `retag`, `mask_iotag`, `mask_vlanid`, `mask_macaddr` and `iotag`.

**Comment by vladimiroltean** [comment]
Not really a bug. Those additional fields you see in `sja1105-tool config modify l2-address-lookup-table` are for the P/Q/R/S series. They are kept in a common structure and unpacked into the binary staging area based on device ID: https://github.com/openil/sja1105-tool/blob/master/src/tool/config-modify.c#L165-L224
You should be able to read/write the fields that E/T support with no problem.

**Comment by sylane** [comment]
You say I just need to put dummy data in the XML files ? because if I don't specify these fields the tool refuse to load the file.

**Comment by vladimiroltean** [comment]
Oh, ok, I didn't think about that.
You could either put dummy data, or you should be able to add some conditionals based on `config->device_id` in `src/tool/xml/write/l2-lookup.c` and `src/tool/xml/read/l2-lookup.c` so it doesn't attempt to access the extra data at all.
