### ISSUE TITLE
User manual for the SJA1105QEL (vlan double tagging)

### ISSUE THREAD

**Issue by sylane** [openil/sja1105-tool#40]
Hi,
It seems that the SJA1105TEL is not cutting it for our prototype because we need to do TSN and SPBV at the same time. We are thinking in switching to the SJA1105QEL that is supposed to support double  tagging but I cannot find any documentation anywhere. I see there is some support for this chip in this tool so you must know where to find some documentation, where can I find it ?

**Comment by vladimiroltean** [comment]
There doesn't appear to be any public version of UM11040 that I can link you to. You should be able to get a copy under NDA by contacting your NXP representative though.
