### ISSUE TITLE
With the SJA1105Q, how do you add a second VLAN ID to all packets that only have one ?

### ISSUE THREAD

**Issue by sylane** [openil/sja1105-tool#44]
I am working on a SPBV router prototype, and I am investigating how this could be done with the SJA1105Q. I am reading the documentation (UM11040) but I couldn't find how it would be possible to add a S-Tag to packets that already have a C-Tag. To implement SPBV I would need to support the following on a subset of the ports:

  - Drop double-tagged traffic (this looks supported).
  - Add a S-Tag to all ingress packets with or without C-Tag to isolate the external traffic from the internal routing algorithm (couldn't find how to do that).
  - Drop the S-Tag from egress packets; if a packet had a vid before adding the S-Tag it should be kept; if the packet had no vid before adding the S-Tag there shouldn't be any (couldn't find how to do that either).

This is required so the shortest path bridging routing uses the S-Tag and the traffic can still use any VLAN they want.

**Comment by vladimiroltean** [comment]
The SJA1105 switch family does not support pushing and popping of VLAN tags for Q-in-Q operation.
