### ISSUE TITLE
[Bug] Broken link for downloading the gcc component from linaro cross-toolchain

### ISSUE THREAD

**Issue by JayachandranRameshBabu** [openil/sja1105-tool#49]
Hello,
It seems like the web link to download the packages(gcc) from linaro cross-toolchain has been updated. The attached patch here fixes the README.md 

Package link: https://releases.linaro.org/components/toolchain/binaries/6.3-2017.05/arm-linux-gnueabihf/

[ReadMe_Patch.zip](https://github.com/openil/sja1105-tool/files/3422310/ReadMe_Patch.zip)

Regards,
Jayachandran

**Comment by vladimiroltean** [comment]
Hi Jayachandran,

Please submit a normal pull request.
Also please take the opportunity to point to the latest toolchain binaries which currently means gcc 7.4.1: https://releases.linaro.org/components/toolchain/binaries/latest-7/arm-linux-gnueabihf/

Regards,
-Vladimir

**Comment by JayachandranRameshBabu** [comment]
Hello Vladimir,

Thanks for your comments. Please find the pull request #50 

Regards,
Jayachandran Ramesh Babu
