### ISSUE TITLE
zynq7020 with sja1105

### ISSUE THREAD

**Issue by tccxy** [openil/sja1105-tool#52]
hi
Now I am using zynq7020 and sja1105, may I ask if this tool is available on the zynq platform

**Comment by vladimiroltean** [comment]
The sja1105-tool is a user space program whose only runtime dependency on the kernel is CONFIG_SPI_SPIDEV=y and a DTS binding for your device with compatible = "rohm,dh2228fv".

**Comment by tccxy** [comment]
thanks a lot
