### ISSUE TITLE
zynq7020 with sja1105

### ISSUE THREAD

**Issue by tccxy** [openil/sja1105-tool#53]
hi
when i use sja1105-tool in zynq 7020 platform
sja1105-tool requst sja1105.bin
how can i get it ?

or 

em..

What can I do to drive sja1105 to work

root@autobrain:~# sja1105-tool config save bug.xml
Staging area /lib/firmware/sja1105.bin does not exist!
root@autobrain:~# ls /dev/spidev1.0               
/dev/spidev1.0
root@autobrain:~# ls /dev/spidev1.0 -l
crw-------    1 root     root      153,   0 Jan  1  1970 /dev/spidev1.0
root@autobrain:~# 
root@autobrain:~# sja1105-tool config default ls1021atsn
could not open /lib/firmware/sja1105.bin for write
root@autobrain:~# sja1105-tool status general           
Unrecognized Device ID 0xffffffff
sja1105_spi_configure failed
root@autobrain:~# 
thanks a lot

**Comment by vladimiroltean** [comment]
Hi,
The sja1105.bin is what the sja1105-tool produces with the "config default", "config load" and "config modify" commands, and what it sends to the switch with "config upload".
Your issue however is that the switch doesn't want to talk to you. The sja1105-tool is asking for device id and the MISO line is high. Either you missed the SPI bus, chip select or the frequency is bad.

**Comment by tccxy** [comment]
thank u very much
I'll debug spi communication first

**Comment by tccxy** [comment]
hi
for test spi communication or test sja1105
the first step i should do is what ??
use the cmd 
sja1105-tool reg xxx 
or 
sja1105-tool status general 
i will see the device id 0x9e00030e ??
is right??

thanks  alot
