### ISSUE TITLE
How to configure LS1021ATSN with sja1105-tool , so that vlan tag of export stream is not deleted

### ISSUE THREAD

**Issue by liu-jeff** [openil/sja1105-tool#56]
How to configure LS1021ATSN with sja1105-tool , so that vlan tag of export stream is not deleted

**Comment by vladimiroltean** [comment]
You need to edit the `vlan-lookup-table` from your sja1105-tool xml and set the corresponding bits of `tag_port` for your ports on which you want the VLAN to be sent as tagged.
Man page is [here](https://github.com/openil/sja1105-tool/blob/master/docs/md/sja1105-tool-config-format.5.md#vlan-lookup-table).
Switch manual is [here](https://www.nxp.com/docs/en/user-guide/UM10944.pdf).

**Comment by liu-jeff** [comment]
> You need to edit the `vlan-lookup-table` from your sja1105-tool xml and set the corresponding bits of `tag_port` for your ports on which you want the VLAN to be sent as tagged.
> Man page is [here](https://github.com/openil/sja1105-tool/blob/master/docs/md/sja1105-tool-config-format.5.md#vlan-lookup-table).
> Switch manual is [here](https://www.nxp.com/docs/en/user-guide/UM10944.pdf).
first,very thank you,Can you give me an example? I still haven't figured out how to use tag_port to make my ETH3 exit stream a stream with a valn tag.

**Comment by vladimiroltean** [comment]
First of all, the ETH3 label on the chassis is just a label. The switch port numbering is completely different, see [here](https://github.com/openil/sja1105-tool#port-numbering-on-the-nxp-ls1021atsn-board). You need to use the number of the chip port.
The default sja1105-tool xml puts a pvid of 0 for each port, and only adds VLAN 0 to the VLAN table. You can start by making tag_port equal to 0x1f, aka make all ports send traffic as tagged, to make sure the feature works. Then you can only enable BIT(2) (aka 0x4), for your ETH3 port.
Then you can add more VLANs to the VLAN table.

**Comment by liu-jeff** [comment]
> First of all, the ETH3 label on the chassis is just a label. The switch port numbering is completely different, see [here](https://github.com/openil/sja1105-tool#port-numbering-on-the-nxp-ls1021atsn-board). You need to use the number of the chip port.
> The default sja1105-tool xml puts a pvid of 0 for each port, and only adds VLAN 0 to the VLAN table. You can start by making tag_port equal to 0x1f, aka make all ports send traffic as tagged, to make sure the feature works. Then you can only enable BIT(2) (aka 0x4), for your ETH3 port.
> Then you can add more VLANs to the VLAN table.

I can now grab the vlan package, but it seems that iperf, ping these will not work, is it necessary to remove the vlan tag for the three or more packages?

**Comment by vladimiroltean** [comment]
You need to add a VLAN sub-interface with "ip link" on eth2 to decode the VLAN ID, if that is different than 0. If it is zero you should not need to do that.
For iperf, you also need to increase the MTU of the switch ports (MAXLEN field of the 45 policer entries) with 4 (the length of the VLAN tags).

**Comment by liu-jeff** [comment]
> You need to add a VLAN sub-interface with "ip link" on eth2 to decode the VLAN ID, if that is different than 0. If it is zero you should not need to do that.
> For iperf, you also need to increase the MTU of the switch ports (MAXLEN field of the 45 policer entries) with 4 (the length of the VLAN tags).

So how do you set the MTU of the port?

**Comment by vladimiroltean** [comment]
Like I just said, search for MAXLEN in the xml and increase it by 4.

**Comment by liu-jeff** [comment]
![image](https://user-images.githubusercontent.com/50905379/69427143-de44cf00-0d69-11ea-8c63-ed1de3365a5e.png)
you look ,next what can i do?

**Comment by vladimiroltean** [comment]
sja1105-tool config save tmp.xml
Replace 0x5ee (1518 bytes) with 0x5f2 (1522 bytes) in tmp.xml
sja1105-tool config load -f tmp.xml

**Comment by liu-jeff** [comment]
> sja1105-tool config save tmp.xml
> Replace 0x5ee (1518 bytes) with 0x5f2 (1522 bytes) in tmp.xml
> sja1105-tool config load -f tmp.xml
Can you modify it by command?

**Comment by vladimiroltean** [comment]
```
for port in $(seq 0 4); do
    for prio in $(seq 0 7); do
        sja1105-tool config modify l2-policing-table[$((${port}*8 + ${prio}))] maxlen 1522
    done
done
sja1105-tool config upload
```

**Comment by liu-jeff** [comment]
> ```
> for port in $(seq 0 4); do
>     for prio in $(seq 0 7); do
>         sja1105-tool config modify l2-policing-table[$((${port}*8 + ${prio}))] maxlen 1522
>     done
> done
> sja1105-tool config upload
> ```

I do it ,but Iperf and ping still can't work

**Comment by vladimiroltean** [comment]
Please share port counters.

**Comment by liu-jeff** [comment]
> Please share port counters.

![image](https://user-images.githubusercontent.com/50905379/69431154-223bd200-0d72-11ea-9ca5-d8645dafb6a3.png)
![image](https://user-images.githubusercontent.com/50905379/69431207-38499280-0d72-11ea-9ef7-3b5911c9ab23.png)
![image](https://user-images.githubusercontent.com/50905379/69431363-8f4f6780-0d72-11ea-816b-48ddcb5ec6ba.png)

Now, my stream outlet is ETH3, so I set the tag_port to 2, but I didn't catch the vlan package on the ETH3 exit computer.

**Comment by vladimiroltean** [comment]
Those are not port counters.
`sja1105-tool status port`.

**Comment by liu-jeff** [comment]
> sja1105-tool status port

![image](https://user-images.githubusercontent.com/50905379/69431640-18ff3500-0d73-11ea-99f3-f86094b26c2a.png)

**Comment by liu-jeff** [comment]
> Those are not port counters.
> `sja1105-tool status port`.
![image](https://user-images.githubusercontent.com/50905379/69431800-6b405600-0d73-11ea-80c2-6650a78f116f.png)
Now, I don’t even have the vlan bag.

**Comment by vladimiroltean** [comment]
What is connected to port 1 (ETH2)? Your sender machine, presumably? It says N_CRCERR 706. What link speed is it running at? Gigabit or 100 mbps? Have you seen the "Link speed autonegotiation is not supported." [known issue](https://github.com/openil/sja1105-tool#known-issues)?

**Comment by liu-jeff** [comment]
> What is connected to port 1 (ETH2)? Your sender machine, presumably? It says N_CRCERR 706. What link speed is it running at? Gigabit or 100 mbps? Have you seen the "Link speed autonegotiation is not supported." [known issue](https://github.com/openil/sja1105-tool#known-issues)?

port1(ETH2) is my sender,It is 1000mbps，now,it do not have vlan tag.
![image](https://user-images.githubusercontent.com/50905379/69432029-d7bb5500-0d73-11ea-8a38-e383dc64cb33.png)
I didn't do this step, I don't know how to do it.

**Comment by vladimiroltean** [comment]
Once you get rid of the CRC errors:
```
sja1105-tool config modify vlan-lookup-table[0] tag_port $((1 << 2))
sja1105-tool config upload
```

**Comment by liu-jeff** [comment]
> Once you get rid of the CRC errors:
> 
> ```
> sja1105-tool config modify vlan-lookup-table[0] $((1 << 2))
> ```
![image](https://user-images.githubusercontent.com/50905379/69432507-ccb4f480-0d74-11ea-87f0-5e49f9da2c22.png)


it error

**Comment by vladimiroltean** [comment]
Please check the updated response....

**Comment by liu-jeff** [comment]
> Please check the updated response....
after command ,it do not have vlan tag too

**Comment by vladimiroltean** [comment]
How do you check?

**Comment by liu-jeff** [comment]
> Please check the updated response....

Is it because I have no settings?
![image](https://user-images.githubusercontent.com/50905379/69433828-5cf43900-0d77-11ea-991f-2c08b6f95155.png)

**Comment by liu-jeff** [comment]
> How do you check?

I do not know,I don't know, but I didn't do this because I don't know how to do this step.how to enable BIT(2)(aks 0x4),for ETH3 port

**Comment by vladimiroltean** [comment]
You just did that.
BIT(2) means 1 << 2. Label ETH3 is port 2.

I meant to ask how do you know the frames are not VLAN-tagged.

**Comment by liu-jeff** [comment]
> You just did that.
> BIT(2) means 1 << 2. Label ETH3 is port 2.
> 
> I meant to ask how do you know the frames are not VLAN-tagged.

I picked up a host on ETH3, as an iperf server, and then grabbed the packet through wireshark (already set to grab the vlan package), but did not catch the vlan tag package.

**Comment by vladimiroltean** [comment]
If you set tag_port to 0x1f do you see the VLAN tag?

**Comment by liu-jeff** [comment]
> If you set tag_port to 0x1f do you see the VLAN tag?

after it , Iperf can't

**Comment by liu-jeff** [comment]
> > If you set tag_port to 0x1f do you see the VLAN tag?
> 
> after it , Iperf can't



> If you set tag_port to 0x1f do you see the VLAN tag?

![image](https://user-images.githubusercontent.com/50905379/69434935-975ed580-0d79-11ea-8530-3385b7d6fc68.png)
![image](https://user-images.githubusercontent.com/50905379/69435031-c5441a00-0d79-11ea-9155-62036b1f1755.png)

but do not have tcp vlan package

**Comment by liu-jeff** [comment]
> If you set tag_port to 0x1f do you see the VLAN tag?

ETH2(1) is my iperf sender ,ETH3(2) is my iperf server,
![image](https://user-images.githubusercontent.com/50905379/69436157-cd9d5480-0d7b-11ea-9ee2-7e370e6ecc30.png)
![image](https://user-images.githubusercontent.com/50905379/69436200-dee66100-0d7b-11ea-92c8-c2218f443121.png)
![image](https://user-images.githubusercontent.com/50905379/69436219-e279e800-0d7b-11ea-96f8-858b06002cb2.png)
![image](https://user-images.githubusercontent.com/50905379/69436653-c0cd3080-0d7c-11ea-9a0d-1952b0d7a43d.png)
From the screenshot above, I feel that I have not made a mistake. What do you think is wrong?

**Comment by vladimiroltean** [comment]
I'm sorry, isn't there a VLAN tag with an ID of 0 and a PCP of 7 in your wireshark dump?

**Comment by liu-jeff** [comment]
> I'm sorry, isn't there a VLAN tag with an ID of 0 and a PCP of 7 in your wireshark dump?

I know ，  You can take a look at the screenshot above. The package I sent from iperf is vlan proi 3 not 7,I think there are lots of problems

**Comment by vladimiroltean** [comment]
Are you sending VLAN-tagged traffic or untagged?
If it is untagged, it gets tagged by the switch on the ingress port, with the MAC's VLAN ID and VLAN PRIO.
If it is tagged, the tag from the original frame is kept.

**Comment by liu-jeff** [comment]
> Are you sending VLAN-tagged traffic or untagged?
> If it is untagged, it gets tagged by the switch on the ingress port, with the MAC's VLAN ID and VLAN PRIO.
> If it is tagged, the tag from the original frame is kept.

I am sending untagged,   i know on the ingress port ,it is combined with vlan prio, on egress,it will be deleted,but i want to reserve the tag on egress , According to the above configuration, it seems that this effect can not be achieved

**Comment by liu-jeff** [comment]
> Are you sending VLAN-tagged traffic or untagged?
> If it is untagged, it gets tagged by the switch on the ingress port, with the MAC's VLAN ID and VLAN PRIO.
> If it is tagged, the tag from the original frame is kept.
Can you give me some suggestions

**Comment by vladimiroltean** [comment]
> Can you give me some suggestions

I can't follow your issue, sorry.
The switch tags all untagged frames with an internal VLAN (mac-config-table[vlanid]). By default in sja1105-tool, that VLAN ID is 0.
The VLAN ID of 0 is removed on egress, via vlan-table[tag_port]. So traffic that was untagged at input is still untagged at output.
What you are doing when you are making VID 0 as egress-tagged is that you are making the port-based VLAN (pvid) untagged input and tagged output. So you break untagged communication. In the wireshark screenshot you sent, the board sees the ARP request but the other device doesn't see the ARP reply, because it's not expecting a VLAN tag.
Linux hosts can actually treat 802.1p (VID 0) tagged traffic as untagged, if they have the 8021q module inserted, which adds VID 0 automatically in their rx filter. This probably did not happen in your case though.
So what you need to do, if you want tagged traffic on output, is pick a valid port-based VLAN for the MACs. Arguably the sja1105-tool default of 0 is not very good. You should add the VLAN ID of 1 to your xml and change all ports to tag by default with 1. Then VLAN 0 becomes available for transmitting tagged frames only.
Then you need to think about how your operating system on the sender and the receiver is going to process that VLAN. That is completely outside the scope of this issue, but it might cause you problems nonetheless.
Then, once all of that is figured out and the switch is configured, you look at changes in the port statistics counters to figure out where and why the switch drops frames. It may or may not be related to VLANs.
Once that is clear as well, you should formulate more clearly what your issue is. I think you achieved the stated goal of not removing the VLAN tag for VID 0 on egress, and that we're talking about something else here.

**Comment by liu-jeff** [comment]
> > Can you give me some suggestions
> 
> I can't follow your issue, sorry.
> The switch tags all untagged frames with an internal VLAN (mac-config-table[vlanid]). By default in sja1105-tool, that VLAN ID is 0.
> The VLAN ID of 0 is removed on egress, via vlan-table[tag_port]. So traffic that was untagged at input is still untagged at output.
> What you are doing when you are making VID 0 as egress-tagged is that you are making the port-based VLAN (pvid) untagged input and tagged output. So you break untagged communication. In the wireshark screenshot you sent, the board sees the ARP request but the other device doesn't see the ARP reply, because it's not expecting a VLAN tag.
> Linux hosts can actually treat 802.1p (VID 0) tagged traffic as untagged, if they have the 8021q module inserted, which adds VID 0 automatically in their rx filter. This probably did not happen in your case though.
> So what you need to do, if you want tagged traffic on output, is pick a valid port-based VLAN for the MACs. Arguably the sja1105-tool default of 0 is not very good. You should add the VLAN ID of 1 to your xml and change all ports to tag by default with 1. Then VLAN 0 becomes available for transmitting tagged frames only.
> Then you need to think about how your operating system on the sender and the receiver is going to process that VLAN. That is completely outside the scope of this issue, but it might cause you problems nonetheless.
> Then, once all of that is figured out and the switch is configured, you look at changes in the port statistics counters to figure out where and why the switch drops frames. It may or may not be related to VLANs.
> Once that is clear as well, you should formulate more clearly what your issue is. I think you achieved the stated goal of not removing the VLAN tag for VID 0 on egress, and that we're talking about something else here.
So I need to change the vlan id for the stream of the ingress? Like 3 not 0

**Comment by vladimiroltean** [comment]
> So I need to change the vlan id for the stream of the ingress? Like 3 not 0

I only said it needs to be different than the port-based default. You can change either of them.

**Comment by liu-jeff** [comment]
> > So I need to change the vlan id for the stream of the ingress? Like 3 not 0
> 
> I only said it needs to be different than the port-based default. You can change either of them., I will try it.

**Comment by liu-jeff** [comment]
> > So I need to change the vlan id for the stream of the ingress? Like 3 not 0
> 
> I only said it needs to be different than the port-based default. You can change either of them.

Thank you ,I will try it!

**Comment by liu-jeff** [comment]
> > So I need to change the vlan id for the stream of the ingress? Like 3 not 0
> 
> I only said it needs to be different than the port-based default. You can change either of them.
I changed a vlan id at the entrance and found that it was directly unreasonable.
